services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - REDIS_HOST=valkey
      - QDRANT_HOST=qdrant
      - NODE_ENV=production
      - UV_THREADPOOL_SIZE=8
      - MAX_OLD_SPACE_SIZE=4096
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - valkey
      - qdrant
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  valkey:
    image: valkey/valkey
    ports:
      - 6379:6379

  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: